### PR TITLE
Attempt to fix warnings from calc_addrs.cl compile

### PR DESCRIPTION
**Pull request by utdrmac**
```
--- calc_addrs.cl.orig  2014-01-25 17:25:39.000000000 -0600
+++ calc_addrs.cl   2014-01-25 17:43:42.000000000 -0600
@@ -209,6 +209,36 @@

 #define bn_iter(e) iter_8(e)

+/*
+ * Prototypes
+ */
+void bn_lshift1(bignum *bn);
+void bn_rshift(bignum *bn, int shift);
+void bn_rshift1(bignum *bn);
+void bn_rshift1_2(bignum *bna, bignum *bnb);
+int bn_ucmp_ge(bignum *a, bignum *b);
+int bn_ucmp_ge_c(bignum *a, __constant bn_word *b);
+void bn_neg(bignum *n);
+bn_word bn_uadd_words_seq(bn_word *r, bn_word *a, bn_word *b);
+bn_word bn_uadd_words_c_seq(bn_word *r, bn_word *a, __constant bn_word *b);
+bn_word bn_usub_words_seq(bn_word *r, bn_word *a, bn_word *b);
+bn_word bn_usub_words_c_seq(bn_word *r, bn_word *a, __constant bn_word *b);
+bn_word bn_uadd_words_vliw(bn_word *r, bn_word *a, bn_word *b);
+bn_word bn_uadd_words_c_vliw(bn_word *r, bn_word *a, __constant bn_word *b);
+bn_word bn_usub_words_vliw(bn_word *r, bn_word *a, bn_word *b);
+bn_word bn_usub_words_c_vliw(bn_word *r, bn_word *a, __constant bn_word *b);
+void bn_mod_add(bignum *r, bignum *a, bignum *b);
+void bn_mod_sub(bignum *r, bignum *a, bignum *b);
+void bn_mod_lshift1(bignum *bn);
+void bn_mul_mont(bignum *r, bignum *a, bignum *b);
+void bn_from_mont(bignum *rb, bignum *b);
+void bn_mod_inverse(bignum *r, bignum *n);
+void sha2_256_init(uint *out);
+void sha2_256_block(uint *out, uint *in);
+void ripemd160_init(uint *out);
+void ripemd160_block(uint *out, uint *in);
+void hash_ec_point(uint *hash_out, __global bn_word *xy, __global bn_word *zip);
+int hash160_ucmp_g(uint *a, __global uint *bound);

 /*
  * Bitwise shift
@@ -531,7 +561,7 @@
    bn_word tea, teb, c, p, s, m;

 #if !defined(VERY_EXPENSIVE_BRANCHES)
-   int q;
+   uint q;
 #endif

    c = 0;
@@ -667,7 +697,7 @@
 bn_mod_inverse(bignum *r, bignum *n)
 {
    bignum a, b, x, y;
-   int shift;
+   uint shift;
    bn_word xc, yc;
    for (shift = 0; shift < BN_NWORDS; shift++) {
        a.d[shift] = modulus[shift];
```

### CODE REVIEW

**Comment by BlinkyStitt** [comment]
I don't think this is the PR you meant to make.  It has my master branch, but not your patch and your patch is the only thing I think it should have.

**Comment by utdrmac** [comment]
Sorry. I don't understand all this git stuff. I did not want to have to branch/clone myself just to generate a pull request. Seemed much simpler to paste the diff in here/issue and ask it to be applied.

**Comment by BlinkyStitt** [comment]
I fixed this on my fork with https://github.com/WyseNynja/vanitygen/pull/10

**Comment by utdrmac** [comment]
I guess this can be closed since WyseNynja fixed it

**Pull request closed without merging**
