### PR TITLE
Make it work on Mac OS X

### PR DESCRIPTION
**Pull request by henrikssn**
*Changed one include for running oclvanitygen on osx
*Added makefile for osx
*Added INSTALL file

### CODE REVIEW

**Comment by henrikssn** [comment]
Uhmm, It builds ok on my fork, but when I merged in latest commits from you it stopped working. Error output by compiler is http://paste.pocoo.org/show/450657/

**Comment by samr7** [comment]
CL_CALLBACK appears to be new to OpenCL 1.1, and mostly for the benefit of Windows.  Anyway, try adding something along the lines of:

#ifndef CL_CALLBACK
#define CL_CALLBACK
#endif

to the **APPLE** section that you added to oclvanitygen.c.  Otherwise, looks really good, a lot simpler than I was expecting!

**Comment by henrikssn** [comment]
Yep, fixed the problem, thanks! Now oclvanitygen compiles with no errors.

Still got problems with compiling kernel on my 6490M: http://paste.pocoo.org/show/450721/ It works when choosing my SB cpu as opencl device...

**Comment by samr7** [comment]
This looks like that bizarre error you ran into in the past, and I'm still stumped.  You might be correct about the command queue properties parameter not being accepted, maybe it would work if the third argument was CL_QUEUE_PROFILING_ENABLE instead of 0.

**Comment by henrikssn** [comment]
Yes, indeed it is. I tried to change that value now but I get the same result. It should run the same code whatever I run it on integrated GPU or dedicated GPU, right? It's funny how it works on integrated but not on dedicated.

**Comment by samr7** [comment]
I can't cite the source, but remember reading somewhere about folks who were having trouble running OpenCL programs on laptops with discrete, switchable GPUs.  Somehow the GPU was being disabled by the operating system and they couldn't figure out how to turn it on.  Does your machine do that?  How does that work on OS X?

According to http://www.waitwaittheresmore.com/?p=57, the discrete graphics device is supposed to be turned on immediately when you start oclvanitygen.  Hmmm, maybe there's a step it's missing?  They also claim the discrete graphics is turned on when you plug in an external display.

**Comment by henrikssn** [comment]
Actually it is not activated by default but I found a way to manually switch it on. Now I no longer get the INVALID_VALUE error but I get segmentation error instead :(

Would be nice if any mac pro user could try this and see if he gets same error.

**Comment by samr7** [comment]
I added a new safe mode option (-S) to oclvanitygen in git.  Try it out, let me know if it works around the crash.

**Comment by henrikssn** [comment]
Tried it, still get "segmentation error" :/

Is there an opencl test suite so you know everything you are using in oclvanitygen really works on mac?

**Comment by samr7** [comment]
Does it still crash at the compile step, or does it get past that?

I don't have a device side test suite for the oclvanitygen kernels yet.

Also, what steps did you take to enable your discrete GPU?  Is it necessary to do this when you run an OpenCL miner, or does the miner somehow enable the GPU on its own?

**Comment by henrikssn** [comment]
It crashes on compilation, see bash dump: http://paste.pocoo.org/show/451169/

I am able to write a small python program which adds two arrays in parallell and it runs fine on discrete card. I made a bad (non-successful) try to redo this in C, but from an OpenCL-perspective it shouldn't matter which lang you are using, right?

I use a tool called "gfxCardStatus" which enables discrete-only. I dont think I had to do anything to get poclbm running, I will re-check that.

**Comment by samr7** [comment]
I see!  So the OS X compiler still doesn't like it, even with safe mode turned on.

Safe mode will only try to turn off the #pragma unroll directives, so there is likely something else about the program that is causing the compiler to choke.

If you're up for a more involved troubleshooting process --

The next step is to edit the calc_addrs.cl source and cover all the __kernel functions with a big "#if 0".  There should be four such functions that aren't already disabled.  At this point, the OpenCL program should compile without crashing, but oclvanitygen will fail because it won't be able to find the kernel functions it needs.  Next, uncomment one of the kernel functions, and try compiling again.  If you repeat this process a few times, you will be able to isolate the cause of the compiler crash, and you'll probably find that it is only necessary to comment some specific lines in one of the kernel functions to avoid the crash.

Or, perhaps removing all of the #pragma lines will fix it.

And absolutely, the language used to implement the host program is mostly irrelevant for OpenCL.

**Comment by henrikssn** [comment]
I tried to #if 0 the kernels and when adding a dummy kernel and disabling all four it does compile, but on each one of the others I get the segmentation error.

EDIT: That is, when enabling only one kernel and disabling the others I still get a segmentation error, no matter which kernel I choose.

Is there any function you use in all the kernels?

**Comment by samr7** [comment]
That's good progress.

There are some bignum arithmetic functions used by all kernels, like bn_mul_mont(), bn_usub_c().  You can try targeting them individually if you feel a hunch.

Next, comment out all kernels except the first kernel, comment out all the code inside the first kernel, so that it's effectively an empty kernel, and make sure it compiles.  Then determine just how much of the first kernel you can uncomment before it crashes.  Probably it will be at the first bn_mod_sub.

Does the OS X OpenCL stack have a CPU device that you can try?

**Comment by henrikssn** [comment]
Hmm, this is getting mroe and more weird... I tried to change calc_addr.cl to this: http://paste.pocoo.org/show/452168/

It still reports "Segmentation fault" on compilation. I think there is a problem with the OpenCL stack or maybe something in oclvanitygen which does something not compatible with mac. Funny thing is that OpenCL is Apple-stuff :)

How do I know if my OpenCL stack has a CPU device?

**Comment by samr7** [comment]
That kernel you pasted might not technically be correct.  The __global qualifier is only supposed to be associated with pointers, and you're using it with plain ints.  So, convert the parameters to int *, or get rid of __global.

If you have both an OpenCL CPU device and GPU device, and run oclvanitygen without a -d flag, it will fail to start and list all known OpenCL platforms/devices.  If you can start it without -d, then you only have one device and that's presumably your GPU.

**Pull request merged**
